const API=(localStorage.getItem("fz_admin_api")||"").replace(/\/$/,"");const token=()=>localStorage.getItem("fz_admin_token")||"";
const sections=[["dashboard","Command Center"],["users","Users"],["reports","Reports & Cases"],["content","Content"],["live","Live Control"],["clubs","Clubs"],["creator-agency","Creator & Agency Portal"],["coins","Coin Purchases"],["wallets","Wallet & Ledger"],["payouts","Payouts"],["verification","KYC & Verification"],["notifications","Notifications"],["analytics","Analytics"],["audit","Admin Audit"],["roles","Roles & Permissions"],["settings","Settings"],["law","Law Enforcement"]];
let state={section:"dashboard",data:null,error:""};
async function api(path,opts={}){if(!API)throw new Error("Set the backend API URL in Settings first.");const r=await fetch(API+path,{...opts,headers:{"Content-Type":"application/json","Authorization":"Bearer "+token(),...(opts.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||j.message||("HTTP "+r.status));return j}
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function shell(content){return `<div class="shell"><aside class="side"><div class="brand"><b>Frenzone</b> Admin</div><nav class="nav">${sections.map(([k,n])=>`<button data-nav="${k}" class="${state.section===k?"active":""}">${n}</button>`).join("")}</nav></aside><main class="main">${content}</main></div>`}
function head(t,s=""){return `<div class="top"><div><div class="title">${t}</div><div class="muted">${s}</div></div><button class="btn secondary" data-refresh>Refresh</button></div>`}
function metrics(items){return `<div class="grid">${items.map(x=>`<div class="card"><div class="muted">${x[0]}</div><div class="metric">${esc(x[1])}</div></div>`).join("")}</div>`}
function panel(title,body){return `<div class="panel"><h3>${title}</h3>${body}</div>`}
function table(cols,rows){return `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.join(""):`<tr><td colspan="${cols.length}" class="empty">No records</td></tr>`}</tbody></table>`}
async function load(){
 state.error="";try{
 if(state.section==="dashboard")state.data=await api("/admin-api/dashboard/stats");
 else if(state.section==="users")state.data=await api("/admin-api/users?perPage=50");
 else if(state.section==="reports")state.data=await api("/admin-api/moderation/cases?perPage=50");
 else if(state.section==="content")state.data=await api("/admin-api/content?limit=100");
 else if(state.section==="live")state.data=await api("/admin-api/live/active");
 else if(state.section==="clubs")state.data=await api("/admin-api/clubs");
 else if(state.section==="audit")state.data=await api("/admin-api/audit?perPage=100");
 else if(state.section==="creator-agency"){const [creators,agencies,relationships]=await Promise.all([api("/admin-api/creator-agency/creators"),api("/admin-api/creator-agency/agencies"),api("/admin-api/creator-agency/relationships")]);state.data={creators:creators.creators||[],agencies:agencies.agencies||[],relationships:relationships.relationships||[]};}
 else if(state.section==="wallets")state.data=await api("/admin-api/finance/ledger");
 else if(state.section==="payouts")state.data=await api("/admin-api/finance/payouts");
 else if(state.section==="analytics")state.data=await api("/admin-api/analytics/overview");
 else if(state.section==="notifications")state.data=await api("/admin-api/notifications/campaigns");
 else if(state.section==="law")state.data=await api("/admin-api/moderation/cases?perPage=100");
 else state.data={};
 }catch(e){state.error=e.message;state.data={}}render()}
function dashboard(){const s=state.data?.stats||{};return head("Command Center","Frenzone Live operational overview")+metrics([["Users",s.users||0],["Active Live",s.liveStreams||0],["Pending Reports",s.pendingReports||0],["Revenue Today",s.revenueToday||0]])+panel("Platform health",`<div class="toolbar"><span class="badge">Posts ${s.posts||0}</span><span class="badge">Reels ${s.reels||0}</span><span class="badge">Verified ${s.verified||0}</span><span class="badge">Active today ${s.activeToday||0}</span></div>`)}
function users(){const a=state.data?.users||[];return head("Users","Search, review and administer Frenzone accounts")+panel("User directory",table(["User","Email","Verified","Live","Status","Action"],a.map(u=>`<tr><td>${esc(u.username||u.firstname||u._id)}</td><td>${esc(u.email||"")}</td><td>${u.isVerified?"Yes":"No"}</td><td>${u.liveAccess?"Granted":"No"}</td><td>${u.banned?'<span class="dangerText">Banned</span>':'<span class="ok">Active</span>'}</td><td><button class="btn secondary" data-user="${u._id}">Open</button></td></tr>`)))}
function reports(){const a=state.data?.cases||[];return head("Reports & Cases","Unified moderation queue for users and content")+panel("Case queue",table(["Case","Target","Priority","Status","Reports","Created"],a.map(x=>`<tr><td>${esc(x.caseNumber)}</td><td>${esc(x.targetType)}</td><td>${esc(x.priority)}</td><td><span class="badge">${esc(x.status)}</span></td><td>${x.reports?.length||0}</td><td>${new Date(x.createdAt).toLocaleString()}</td></tr>`)))}
function content(){const a=state.data?.content||[];return head("Content","Posts and reels moderation")+panel("Content",table(["Type","Author","Description","Flagged","Created"],a.map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.author?.username||"")}</td><td>${esc((x.description||"").slice(0,90))}</td><td>${x.flagged?'<span class="warn">Yes</span>':'No'}</td><td>${new Date(x.createdAt).toLocaleString()}</td></tr>`)))}
function live(){const a=state.data?.streams||[];return head("Live Control","Monitor active Frenzone live streams")+panel("Active streams",table(["Stream","Host","Heartbeat","Action"],a.map(x=>`<tr><td>${esc(x._id)}</td><td>${esc(x.userid||"")}</td><td>${esc(x.lastHeartbeatAt||"")}</td><td><button class="btn danger" data-stoplive="${x._id}">Terminate</button></td></tr>`)))}
function clubs(){const a=state.data?.clubs||[];return head("Clubs","Club owners, prices and membership operations")+metrics([["Allowed monthly tiers","$3.99 / $6.99 / $9.99"],["Clubs",a.length],["Creator share","42%"],["Frenzone share","28%"]])+panel("Clubs",table(["Club","Owner","Monthly Fee","Members"],a.map(x=>`<tr><td>${esc(x.name||x._id)}</td><td>${esc(x.userid?.username||"")}</td><td>$${Number(x.fee||0).toFixed(2)}</td><td>${x.members?.length||0}</td></tr>`)))}
function creatorAgency(){const d=state.data||{},cr=d.creators||[],ag=d.agencies||[],rel=d.relationships||[];return head("Creator & Agency Portal","Applications, creators, agencies, relationships and financial operations")+metrics([["Approved creators",cr.length],["Agencies",ag.length],["Relationships",rel.length],["Frenzone creator-monetization share","28%"]])+panel("Agencies",table(["Agency","Owner","Country","Status"],ag.map(x=>`<tr><td>${esc(x.agency_name)}</td><td>${esc(x.owner_user_id?.username||x.owner_user_id?.email||"")}</td><td>${esc(x.country)}</td><td><span class="badge">${esc(x.status)}</span></td></tr>`)))+panel("Creator relationships",table(["Creator","Agency","Status","Joined"],rel.map(x=>`<tr><td>${esc(x.creator_id?.username||"")}</td><td>${esc(x.agency_id?.agency_name||"")}</td><td><span class="badge">${esc(x.status)}</span></td><td>${esc(x.joined_at||"")}</td></tr>`)))}
function wallets(){const a=state.data?.entries||[];return head("Wallet & Ledger","Append-only financial ledger")+panel("Ledger",table(["Time","Account","Type","Amount","Coins","Reference"],a.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString()}</td><td>${esc(x.accountType)}</td><td>${esc(x.entryType)}</td><td>${Number(x.amount||0).toFixed(2)} ${esc(x.currency)}</td><td>${esc(x.coins||0)}</td><td>${esc(x.reference)}</td></tr>`)))}
function payouts(){const a=state.data?.payouts||[];return head("Payouts","Creator and agency payout administration")+panel("Payout queue",table(["User","Method","Amount","Net","Status","Created","Statement"],a.map(x=>`<tr><td>${esc(x.userId?.username||x.userId?.email||"")}</td><td>${esc(x.payoutMethod)}</td><td>${Number(x.amount||0).toFixed(2)}</td><td>${Number(x.netAmount||0).toFixed(2)}</td><td><span class="badge">${esc(x.status)}</span></td><td>${new Date(x.createdAt).toLocaleString()}</td><td>${x.userId?._id?`<button class="btn secondary" data-payout-csv="${x.userId._id}">CSV</button> <button class="btn secondary" data-payout-print="${x.userId._id}">Print / PDF</button>`:""}</td></tr>`)))}
function analytics(){const a=state.data?.analytics||{};return head("Analytics","Operational metrics based only on data currently logged by Frenzone")+metrics([["Total users",a.users?.total||0],["New users 30d",a.users?.new30||0],["Live sessions 30d",a.live?.count||0],["Gross revenue 30d","$"+Number(a.revenue?.gross||0).toFixed(2)]])+panel("Engagement & content",`<div class="toolbar"><span class="badge">Activities 7d ${esc(a.engagement?.activities7||0)}</span><span class="badge">Posts 30d ${esc(a.content?.posts30||0)}</span><span class="badge">Reels 30d ${esc(a.content?.reels30||0)}</span><span class="badge">Live hours ${Number((a.live?.durationSeconds||0)/3600).toFixed(1)}</span></div><div class="notice">${esc(a.note||"")}</div>`)}
function notifications(){const a=state.data?.campaigns||[];return head("Push Broadcasting","Rich push, audience targeting, deep links, testing and scheduling")+panel("Compose push",`<div class="formGrid"><input id="ntitle" class="input" placeholder="Notification title"><textarea id="nbody" class="input" placeholder="Message"></textarea><input id="nimage" class="input" placeholder="HTTPS image URL (optional)"><select id="naud"><option>ALL</option><option>ACTIVE</option><option>INACTIVE</option><option>CREATORS</option><option>AGENCIES</option><option>VERIFIED</option><option>LANGUAGE</option><option>COUNTRY</option><option>SELECTED</option></select><input id="navalues" class="input" placeholder="Languages/countries, comma separated"><input id="nusers" class="input" placeholder="Selected user IDs, comma separated"><select id="ndtype"><option>NONE</option><option>PROFILE</option><option>POST</option><option>CLUB</option><option>LIVE</option><option>URL</option></select><input id="ndtarget" class="input" placeholder="Deep-link target ID or HTTPS URL"><input id="naction" class="input" placeholder="Action label (optional)"><input id="nschedule" class="input" type="datetime-local"><input id="ntestuser" class="input" placeholder="Test user ID"></div><div class="toolbar"><button class="btn secondary" id="testcampaign">Test Send</button><button class="btn secondary" id="schedulecampaign">Schedule</button><button class="btn" id="sendcampaign">Send Now</button></div>`)+panel("Campaign history",table(["Created","Title","Audience","Recipients","Delivered","Failed","Opened","Clicked","Status"],a.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString()}</td><td>${esc(x.title)}</td><td>${esc(x.audience)}${x.audienceValues?.length?` · ${esc(x.audienceValues.join(", "))}`:""}</td><td>${esc(x.recipientCount)}</td><td>${esc(x.successCount)}</td><td>${esc(x.failureCount)}</td><td>${esc(x.openedCount||0)}</td><td>${esc(x.clickedCount||0)}</td><td><span class="badge">${esc(x.status)}</span></td></tr>`)))}
function law(){const a=state.data?.cases||[];return head("Law Enforcement","Restricted case evidence, export and preservation tools")+`<div class="notice">Authorized use only. Exports contain only data Frenzone currently stores. IP-derived location is approximate, not GPS.</div>`+panel("Cases",table(["Case","Target","Priority","Status","Reports","Evidence"],a.map(x=>`<tr><td>${esc(x.caseNumber)}</td><td>${esc(x.targetType)} · ${esc(x.targetId)}</td><td>${esc(x.priority)}</td><td><span class="badge">${esc(x.status)}</span></td><td>${x.reports?.length||0}</td><td><button class="btn secondary" data-evidence="${x._id}">Review</button> <button class="btn secondary" data-csv="${x._id}">CSV</button> <button class="btn secondary" data-print="${x._id}">Print / PDF</button></td></tr>`)))+panel("Evidence package contents",`<div class="evidenceGrid"><div><b>Account</b><br><span class="muted">User ID, username, email/phone when stored, verification and moderation state.</span></div><div><b>Sessions & devices</b><br><span class="muted">IP, approximate location when available, device model/OS, app version and timestamps.</span></div><div><b>Content & reports</b><br><span class="muted">Reported case data, relevant posts and moderation history.</span></div><div><b>Financial</b><br><span class="muted">Transactions and payout records when relevant and authorized.</span></div></div>`)}
function audit(){const a=state.data?.logs||[];return head("Admin Audit","Immutable history of privileged admin actions")+panel("Audit log",table(["Time","Admin","Action","Target","Reason"],a.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString()}</td><td>${esc(x.adminId?.email||x.adminId||"")}</td><td>${esc(x.action)}</td><td>${esc(x.targetType)}</td><td>${esc(x.reason)}</td></tr>`)))}
function generic(){const names=Object.fromEntries(sections);return head(names[state.section]||"Admin","Final Frenzone administration module")+panel("Module",`<div class="empty">Backend integration for this module is being connected to the existing Frenzone services.</div>`)}
function render(){let body=state.error?`<div class="notice">${esc(state.error)}</div>`:"";const fn={dashboard,users,reports,content,live,clubs,"creator-agency":creatorAgency,wallets,payouts,analytics,notifications,audit,law}[state.section]||generic;document.querySelector("#app").innerHTML=shell(body+fn());bind()}
function openAuthorized(path){const reason=prompt("Reason / legal request or case reference for this export?");if(!reason)return;const url=API+path+(path.includes("?")?"&":"?")+"reason="+encodeURIComponent(reason);const w=window.open("","_blank");fetch(url,{headers:{"Authorization":"Bearer "+token()}}).then(async r=>{if(!r.ok){let j=await r.json().catch(()=>({}));throw new Error(j.error||("HTTP "+r.status))}return r.text()}).then(html=>{w.document.open();w.document.write(html);w.document.close()}).catch(e=>{w.close();alert(e.message)})}
function downloadAuthorized(path){const reason=prompt("Reason / legal request or case reference for this export?");if(!reason)return;fetch(API+path+(path.includes("?")?"&":"?")+"reason="+encodeURIComponent(reason),{headers:{"Authorization":"Bearer "+token()}}).then(async r=>{if(!r.ok){let j=await r.json().catch(()=>({}));throw new Error(j.error||("HTTP "+r.status))}return r.blob().then(blob=>({blob,disp:r.headers.get("content-disposition")}))}).then(({blob,disp})=>{const m=/filename="?([^";]+)"?/i.exec(disp||"");const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=m?.[1]||"frenzone-evidence.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}).catch(e=>alert(e.message))}
function notificationPayload(){const audience=document.querySelector("#naud")?.value||"ALL",vals=(document.querySelector("#navalues")?.value||"").split(",").map(x=>x.trim()).filter(Boolean),selected=(document.querySelector("#nusers")?.value||"").split(",").map(x=>x.trim()).filter(Boolean),dt=document.querySelector("#ndtype")?.value||"NONE",target=(document.querySelector("#ndtarget")?.value||"").trim();return {title:document.querySelector("#ntitle")?.value||"",body:document.querySelector("#nbody")?.value||"",audience,audienceValues:vals,selectedUserIds:selected,imageUrl:(document.querySelector("#nimage")?.value||"").trim(),deepLink:{type:dt,targetId:dt==="URL"?"":target,url:dt==="URL"?target:"",actionLabel:(document.querySelector("#naction")?.value||"").trim()}}}
function bind(){document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{state.section=b.dataset.nav;load()});document.querySelector("[data-refresh]")?.addEventListener("click",load);document.querySelector("#sendcampaign")?.addEventListener("click",async()=>{const p=notificationPayload();if(!confirm(`Send this push now to ${p.audience}?`))return;try{await api("/admin-api/notifications/campaigns/send",{method:"POST",body:JSON.stringify(p)});load()}catch(e){if(String(e.message).includes("Large audience confirmation required")){if(!confirm("This is a large broadcast. Confirm sending to the full audience?"))return;try{await api("/admin-api/notifications/campaigns/send",{method:"POST",body:JSON.stringify({...p,confirmLargeAudience:true})});load()}catch(e2){alert(e2.message)}}else alert(e.message)}});document.querySelector("#testcampaign")?.addEventListener("click",async()=>{const p=notificationPayload(),userId=(document.querySelector("#ntestuser")?.value||"").trim();if(!userId)return alert("Enter a test user ID.");try{await api("/admin-api/notifications/campaigns/test",{method:"POST",body:JSON.stringify({...p,userId})});alert("Test push request completed.")}catch(e){alert(e.message)}});document.querySelector("#schedulecampaign")?.addEventListener("click",async()=>{const p=notificationPayload(),v=document.querySelector("#nschedule")?.value;if(!v)return alert("Choose a schedule date and time.");try{await api("/admin-api/notifications/campaigns/schedule",{method:"POST",body:JSON.stringify({...p,scheduledAt:new Date(v).toISOString()})});load()}catch(e){alert(e.message)}});document.querySelectorAll("[data-evidence]").forEach(b=>b.onclick=async()=>{const reason=prompt("Reason / legal request or case reference for viewing evidence?");if(!reason)return;try{const d=await api("/admin-api/law-enforcement/cases/"+b.dataset.evidence+"/evidence?reason="+encodeURIComponent(reason));alert("Evidence package ready. SHA-256: "+d.sha256+"\nUse CSV for the structured export.")}catch(e){alert(e.message)}});document.querySelectorAll("[data-csv]").forEach(b=>b.onclick=()=>downloadAuthorized("/admin-api/law-enforcement/cases/"+b.dataset.csv+"/evidence.csv"));document.querySelectorAll("[data-print]").forEach(b=>b.onclick=()=>openAuthorized("/admin-api/law-enforcement/cases/"+b.dataset.print+"/evidence/print"));document.querySelectorAll("[data-payout-csv]").forEach(b=>b.onclick=()=>downloadAuthorized("/admin-api/law-enforcement/users/"+b.dataset.payoutCsv+"/payout-statement.csv"));document.querySelectorAll("[data-payout-print]").forEach(b=>b.onclick=()=>openAuthorized("/admin-api/law-enforcement/users/"+b.dataset.payoutPrint+"/payout-statement/print"));document.querySelectorAll("[data-stoplive]").forEach(b=>b.onclick=async()=>{const reason=prompt("Reason for terminating this live?");if(!reason)return;try{await api("/admin-api/live/"+b.dataset.stoplive,{method:"DELETE",body:JSON.stringify({reason})});load()}catch(e){alert(e.message)}})}
render();load();